services:
  server:
    build: .
    image: server_image:dev
    container_name: server_container
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      DATABASE_URL: "postgresql://ORM_user:secret@db:5432/secretaria-igreja?schema=public"
  db:
    image: postgres:15.15-bookworm
    container_name: postgres_container
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  adminer: # Servi√ßo para vizualizar o db
    image: adminer:standalone
    restart: on-failure
    ports:
      - "8080:8080"